apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevator-web
  namespace: elevator-map
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elevator-web
  template:
    metadata:
      labels:
        app: elevator-web
    spec:
      containers:
      - name: web
        image: registry.local/elevator-web:latest
        ports:
        - containerPort: 80
