apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elevator-ingress
  namespace: elevator-map
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: elevator-map.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elevator-web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: elevator-api
                port:
                  number: 4000
